---
always_allow_html: true
title: "D214 - Graduate Capstone"
author: "Sean P. Murphy"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
  always_allow_html: true
  html_notebook:
    toc: true
    toc_depth: 3
subtitle: Data Analytics Report
---


\newpage
***
# Introduction
***


\newpage
***
# Part I: Research Question
***
 
A.  Summarize the original real-data research question you identified in task 1. Your summary should include justification for the research question you identified in task 1, a description of the context in which the research question exists, and a discussion of your hypothesis.

 
\newpage
***
# Part II: Data Collection
***
 

B.  Report on your data-collection process by describing the relevant data you collected, discussing one advantage and one disadvantage of the data-gathering methodology you used, and discussing how you overcame any challenges you encountered during the process of collecting your data.

 
\newpage
***
# Part III: Data Extraction and Preparation
***
 

C.  Describe your data-extraction and -preparation process and provide screenshots to illustrate each step. Explain the tools and techniques you used for data extraction and data preparation, including how these tools and techniques were used on the data. Justify why you used these particular tools and techniques, including one advantage and one disadvantage when they are used with your data-extraction and -preparation methods. 

 
\newpage
***
# Part IV: Analysis
***
 

D.  Report on your data-analysis process by describing the analysis technique(s) you used to appropriately analyze the data. Include the calculations you performed and their outputs. Justify how you selected the analysis technique(s) you used, including one advantage and one disadvantage of these technique(s).

 
\newpage
***
# Part V: Data Summary and Implications
***
 

E.  Summarize the implications of your data analysis by discussing the results of your data analysis in the context of the research question, including one limitation of your analysis. Within the context of your research question, recommend a course of action based on your results. Then propose two directions or approaches for future study of the data set.

 
\newpage
***
# Part VI: Submission Standards
***

F.  Acknowledge sources, using in-text citations and references, for content that is quoted.

 

G.  Demonstrate professional communication in the content and presentation of your submission.

\newpage
# References